### ISSUE TITLE
[meta] List of minor web UI enhancements

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin-web#103]
Spoke some with @joshuaboniface and he suggested that minor UI foibles and improvements all be tracked in one master issue with check boxes to track their progress. Should make it easier for UI folks to hop in and help so this is my attempt at compiling the existing minor UI bugfixes/improvements and adding some new ones. 

This list does not include items presumed to be "difficult" or those that are known to require backend work.

* [x] ~~Make clicking on an item's name do something #300~~ 
* [x] Dark overlay staying on #297
* [x] ~~Display time finished - as in more recent emby versions #261~~
* [x] Add confirmation when overwriting image #247 
* [x] ~~Dashboard should show default paths #122~~
* [x] ~~Set default admin panel theme to dark theme #308~~
* [x] ~~Change first install pages to use dark theme #322~~

**Comment by JustAMan** [comment]
First bullet fixed by #26

**Comment by T0W1** [comment]
Alphabet list overlaps Dashboard icon when not fullscreen.
![Fullscreen-Screenshot from 2019-04-29 23-16-59](https://user-images.githubusercontent.com/50248556/57164054-38dd0480-6df3-11e9-9f14-8e0b167c8eb7.png)
![Screenshot at 2019-04-29 23:15:54](https://user-images.githubusercontent.com/50248556/57164057-39759b00-6df3-11e9-9363-a2eace088984.png)

**Comment by T0W1** [comment]
the scroll button overlaps with the 3dots.
![Screenshot from 2019-04-29 21-59-22](https://user-images.githubusercontent.com/50248556/57165021-3b8d2900-6df6-11e9-8dd1-871347c30bfa.png)

also this, there is nothing there.
![Screenshot at 2019-05-03 22:51:06](https://user-images.githubusercontent.com/50248556/57165073-58c1f780-6df6-11e9-8939-7c126367efb1.png)

**Comment by T0W1** [comment]
The Movie and TV Show posters are inconsistent when it comes to showing YEAR.

**Comment by dkanada** [comment]
Since the only item left on the list is already tracked in #107 I think we can close this issue.
