### ISSUE TITLE
[Meta] List to track user customizable theme support

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin-web#72]
Just a "master" list to track known issues working towards user supplied themes.

* [ ]  Make it so themes are not hard coded #68 
* [ ] Move all theme related color codes to theme .css files #69 
* [ ] Add way to upload user themes #70 
* [x] ~~Remove seasonal themes #71~~

**Comment by dkanada** [comment]
After a lot of work trying to separate the web source from the server I dont' think themes should be handled by the server at all, thus closing most of these issues. My eventual goal is to include a `settings.json` file in the web directory that will include options like pagination values (default of 100 up to infinite) and a multiserver toggle at first. If we continue with the theme (heh) of web being separate from server, then the proper thing to do for user themes would just be to copy them over to the themes directory and include an option in `settings.json` to add custom theme locations.

**Comment by JustAMan** [comment]
shoo bot

**Comment by MrTimscampi** [comment]
Some proposal for this:

- Add an API endpoint to GET, ADD and DELETE themes
- Themes are JSON objects with key/value pairs kind of like this:
```json
{
    "primary": "#00a4dc",
    "secondary": "#303030"
}
```
- On the web client, there is only one "theme" CSS file (they're mostly duplicate anyway).
- During bootstrap, the theme API is queried to get the current theme for the server or user
- The colors are stored as CSS variables in the `:root` element
- A polyfill for CSS variables is added (See here: https://www.npmjs.com/package/css-vars-ponyfill)
- When changing the user or server theme, the API is queried and the CSS variables are replaced, thereby updating the colors for the user

We can add a theme editing page to the admin dashboard to add, remove or edit themes, which would make calls to the API as well.

**Comment by sparky8251** [comment]
This idea would also result in letting non-CSS supporting clients support themes which would be huge.

I'm in favor of it.

**Comment by MrTimscampi** [comment]
We probably need some input from @jellyfin/backend for the API part.

**Comment by dkanada** [comment]
So this would break the extensive customization available for themes right now. @grafixeyehero has dome some extremely nice things with purple haze that wouldn't be available with this system.

**Comment by dkanada** [comment]
I also question how many clients would utilize these global themes considering most third party clients will probably want their own style and most of our native clients are either already using web or will probably keep their existing design. Android TV might look good with different primary and secondary colors, but that's about as far as you could go without extensive work to handle custom borders or graphics, which would be a nightmare to support across platforms. Should we really cripple the existing customizability for themes just so we can say it's a new endpoint on the server?

**Comment by mark-monteiro** [comment]
What about this structure to support existing CSS themes, as well as provide variables that other non-HTML clients can also to use:

```json
{
    "themeVariables": {
        "Could be limited to just colors, or also include other things like border-widths, etc.": "",
        "primary": "#00a4dc",
        "secondary": "#303030"

    },
    "customCss: {
       // To support existing CSS-only themes. This css could reference the variables above
    }  
}
```
